name: CI/CD – Streamlit App to Cloud Run

# main 브랜치에 푸시될 때마다 실행
on:
  push:
    branches: [ main ]

# 워크플로우 전체에서 사용되는 환경변수
env:
  GCP_PROJECT: project-176615
  REGION: asia-northeast3
  SERVICE: mathquiz-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) GCP CLI 설치 및 인증
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          export_default_credentials: true

      # 3) Docker 레지스트리 인증
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker

      # 4) 컨테이너 빌드 & GCR 푸시
      - name: Build & Push to GCR
        run: |
          gcloud builds submit \
            --project=${GCP_PROJECT} \
            --region=${REGION} \
            --tag=gcr.io/${GCP_PROJECT}/mathquiz-app \
            .

      # 5) Cloud Run에 배포
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${SERVICE} \
            --image gcr.io/${GCP_PROJECT}/mathquiz-app \
            --project ${GCP_PROJECT} \
            --region ${REGION} \
            --platform managed \
            --allow-unauthenticated \
            --quiet
