name: CI/CD – Streamlit App to Cloud Run

# main 브랜치에 푸시될 때마다 실행
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # 이 job 전체에서 사용할 환경변수
    env:
      GCP_PROJECT: project-176615
      REGION: asia-northeast3
      SERVICE: mathquiz-service
      # IMAGE는 반복 정의하지 않고, 아래 스크립트에서 사용합니다.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: project-176615

      - name: Build & Push to GCR
        run: |
          # 이미지 이름은 직접 문자열로 구성
          IMAGE="gcr.io/${GCP_PROJECT}/mathquiz-app"

          # 1) GCR 인증
          gcloud auth configure-docker

          # 2) Cloud Build로 컨테이너 빌드 & 푸시
          gcloud builds submit \
            --project="${GCP_PROJECT}" \
            --region="${REGION}" \
            --tag="${IMAGE}" \
            .

      - name: Deploy to Cloud Run
        run: |
          IMAGE="gcr.io/${GCP_PROJECT}/mathquiz-app"

          gcloud run deploy "${SERVICE}" \
            --image "${IMAGE}" \
            --project "${GCP_PROJECT}" \
            --region "${REGION}" \
            --platform managed \
            --allow-unauthenticated \
            --quiet
