name: CI/CD – Streamlit App to Cloud Run

# main 브랜치에 푸시될 때마다 실행
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # 환경변수 정의
    env:
      GCP_PROJECT: project-176615
      REGION: asia-northeast3
      SERVICE: mathquiz-service
      IMAGE: gcr.io/${{ env.GCP_PROJECT }}/mathquiz-app

    steps:
      # 1) 소스코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) GCP CLI 설치 및 인증
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          export_default_credentials: true

      # 3) Docker 레지스트리 인증
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker

      # 4) Container 빌드 및 GCR 푸시 (Dockerfile이 repo 루트에 있어야 합니다)
      - name: Build & Push to GCR
        run: |
          gcloud builds submit \
            --project=${{ env.GCP_PROJECT }} \
            --region=${{ env.REGION }} \
            --tag=${{ env.IMAGE }} \
            .

      # 5) Cloud Run에 배포
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image ${{ env.IMAGE }} \
            --project ${{ env.GCP_PROJECT }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --quiet
