name: CI/CD – Streamlit App to Cloud Run

on:
  push:
    branches: [ main ]

env:
  GCP_PROJECT: project-176615
  REGION: asia-northeast3
  SERVICE: mathquiz-service
  IMAGE: gcr.io/project-176615/mathquiz-app   # 레포 루트에 Dockerfile이 있다고 가정
  SOURCE_DIR: .                               # ← Dockerfile 위치. 예: math 로 바꿀 수 있음

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT }}

      # ① Docker 레지스트리 인증 (프롬프트 제거)
      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      # ② Cloud Build로 컨테이너 빌드 & 푸시
      - name: Build & Push image
        run: |
          gcloud builds submit "$SOURCE_DIR" \
            --project="$GCP_PROJECT" \
            --region="$REGION" \
            --tag="$IMAGE" \
            --quiet

      # ③ Cloud Run에 배포
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE" \
            --image "$IMAGE" \
            --project "$GCP_PROJECT" \
            --region "$REGION" \
            --platform managed \
            --allow-unauthenticated \
            --quiet
