[gcp_service_account]
type = "service_account"
project_id = "project-176615"
private_key_id = "d6d11e975cf0fa51fe94f817d3e001461410da9f"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCpGLECKpV8vExy
lv3a2V3JYzRRhQBuRP97ntiQpnLMLw6oTnLpV0/n7iIo8qdsFqDI7XoqNQSCrWWW
rw4qLDQUcJBaPilKoCK199ZoyzIoMckl11mjwcUkpH8UU+S9C+3nGR9TPdx0nXDT
v7WHAhj3vM+uqRHKFVo5tnAg75yfaTIV8GpDPvF+0qF15BcFfUYwE8WNQ1CYVTad
ZgnfzwisSIFxVkmFGpEc2UYw89187/FE0HQ/SWkiS0CRQ71umLGh7koD4TL/wrrM
Dp7I9+QhqgiKWYYmXYOAVMPzTwOXGfqOeoGLV3UYEKszC8Y4quyX3UNdaeeE2AD5
KTAMH3FnAgMBAAECggEAGsrewQkeRnVPZ5ilAFgQlCgz0fbQ6qfkEyJIDiNRbSjH
mcNUUcST1JvWrcZE4Mt1DmESSj28SThQMF/sTqJSXiq3tJTE1h4pYcuzHUeU2umI
hYZpnZjGM9gciowAYjPRrhw86mOS2qdXiTWG/a1HZ3lzLql7OBnKAfr2KUHN/zPZ
yv7DtwWkpxOQCfX01I534IVBaOf4BDoj3JrU/yuxX9clX5S4RZfIX95Zh8+Mmor1
TnzrZ4nb2V/OVHB6AvRCrRMXEVPbkUDKugftsOq9r8/c6eySnuSbrM6AkJzjQ6IP
by5AIcI9UyK+kwBVLNe3idDJQW4eMiAlnYe/hgskgQKBgQDZ4EGiy921+O0tWeBw
DUKNOtbAY3ZEkkZp260pp7dMLkJJn64OgbImEZGVBT3yJAsntbohMDAH6iInTSeS
dCH8rmy0EUf91HTDzCTSZBsvP+CYfS6nKSXxL8aiYovXMzi2W8ZWzAvbSTg6wU/W
mXSzSpKiQJGpchssk1kN4yMQ6wKBgQDGr1uU1WxiQqMCkWnYaVsn0v3cL3yOSXTD
hJ05g2qO2InWOSZDCuaxdmfONVkdMagLmBrQYpfqaMkOgtuECkjPvbfrCmQIeFAJ
Rap+3PZhZGlFmorO7ae66JArDd3mjyN1eV4xc+V1x75c+XPxqfBMMqhu9mamM+mb
QmCTbCyidQKBgClhNTYVIBuylmE5o63EZvJpzWWmvkyRt3vddAroRqDaXE6dXDJ3
IX2nco3p+/TkMZYuJpatD0JBjpEGT1C6a8YQ3qZobdLgqfiR6iBnUN5tdFuh0t1+
rC0dlM08iDCsEsZXsdjEUjAovNwz4NTyOj7fF/Bm8QNMn6qcpZpEnGFXAoGAXY22
lsdD6KSt8wibiU5aoM7lwCcQBEOsWl/4VFt/8lEd3iQ80vawF8HEMUHHe0qlcQgn
IBY8qCC9Azs0t+DL1h3kGyViYuab8TG/jUroLIXGWALj93nKL+VP9SXrZaPis275
nlmPIz1xcn/3S0SUpJx52P3m6b2p8vR3WxNllP0CgYEAgOmdk6oDldPoUS0WuD0M
fPAtZcViwgnzmBqPJj8EXpsFJpJpAVjPcZjYk93JtI0yo+s5buCDy7VCgDSPcXcR
WWEZKXGQNRCRknWJ3vSQK7SBhiVv97JFS79PCmdDzmzzVH1zDJkn6emr7I4E/TJH
ZcSh9h8dknIZ8WkQwvQT5Kk=
-----END PRIVATE KEY-----
"""
client_email = "mathquiz@project-176615.iam.gserviceaccount.com"
client_id = "104568264546331647573"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/mathquiz%40project-176615.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

