[gcp_service_account]
type = "service_account"
project_id = "project-176615"
private_key_id = "3970adbf62b75fc94eec4d72ce9c1ae5a7b39ccc"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC+tGKipqzFXUdA
iU5jFot/sP5jBRFnx4qEj3ojzBtt3GkYgLEMGKwe+pPVpR9bnG7lCXerqqB4u41C
/ipnASKZyOUs7PCATDD/MOPIKi3TblrJSQC2zHNplKY2WsT3q8QmsS1e7SqEdst7
73Z5VUGqDgKhJZLzgjuy2x+nl0vFQo9ZXL3+z7THi5gG89CDG4xKZKfRty5dRrBf
FQjnX88k2nDBmXZZ3i30Z8KvEZUTGfT5hHJtYMff1AFUr/81R2zmGiDloMx7IpmX
bsCCZHGiBqwRWGd0nVpaLhrcUUXe5yFZEG+VP0XzOuuhRrz+xvidBrKD7IzcSg7G
ViOzPK5VAgMBAAECggEADQ+cq8gfkBrd3OkqgbXTEwlDuvNnaESt03tiIZ6CiGku
l3uE5K+x5iNCScEX3zXdEHmwBQVYHTy3JY3zyH825/Ju479Mj3TobCnkh9p/rfni
ZOPHlT12cBY6tgFMeSv98Kp00YoLvevG7vONGS1CJIv2GSRSJrRWM183kUpW6akR
fwIHKl0HFoBFg3VxOliMwOtgMNowgZps0xs1toH55xMdztMdemM3rdM70nfAfGK6
+oDLlBTSuBzJxv06EJ2FUL4wht68jPi6irI03grERAg09Zz3Axuz/hGpxpNsZnve
m1YLueDd0YEUPK+SdNJpfAUfUBlo1NFEpWUQ0OV4JwKBgQDuWH4X/WOst4+tYTBT
mtsx5fADhPm9MudFvwkAErcGTMEY8ie4hcG9S9Tdy23/pnCQbnzmYKE5bVRZT+ZP
ZAxyY3ktyOongxvDRGs4CNVDTcUSHOt2yp7gqPUkTtLi6binhl1VR3qTH2v01qmp
CXhW5hKCqErkShzDTtsE1Qe/gwKBgQDM1IYe7NmZCvkXsRZn2FKn0ZWEFzhGM6UP
VuXqyiApxYh7UVhYBYU8yHYN/+yInMIRZtqZX9p1q1ydZPn99rnMjcdY28sCoupD
F/gCLC8lRagtveedTcG6TAi/yStJ1tosalFI58j+UfJIgcqOE1CcRZAZxdwuE39Q
DHjMdIFbRwKBgDAmwJKoJlLmYqhsUg8R4eaaxXpwiuOmPQLiLTdOkJs9NmWLxmqI
2zMa9s44Iuja/zKun50LOIcZh0jj02uGkt0pK3oMdQG2gw1X7TFM14jZVU7reMZu
+Nn6SEwlgIVHIn71rjVkU2cVmgHEvFHiD+W+ZU7wIPEt59GtRKIdR4txAoGAG9qK
oonyzS0A0ofyVAzGsKt/eYbu0B0VxRA8E8GIviVuedaF/PJDPBDGfQDgWXN3sIYc
E99FBdtXrM+ebzqt6XMeOKcq5CDjWlxYDXOUtazTQeUhKfL49SyBxBLHIDNnV8Ld
atyaKHtcRx/fO5LE03tiLR8K4fkkxu3rP2JYdOECgYAlnHl+P9aHM8d50ZlwY/y4
VQ+c4kO7V8hSducrv764zY40OvGnUlY0wiU5b0Sh6mn5Au/eLr8U2NvUqv+y44T8
fA+J/Rx/k5SgOio9AwI8070ZJZj3NkRFIHGpI7UtW1lVylspIPV4vsyLvCGRn4nm
/O4M6N+1p7f4RYYk50Nb+g==
-----END PRIVATE KEY-----
"""
client_email = "mathquiz@project-176615.iam.gserviceaccount.com"
client_id = "104568264546331647573"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/mathquiz%40project-176615.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

